id: P008018
initial_creation_type: ocr
source_metadata:
  id: bdr:W11847
  title: ཚད་མའི་བསྟན་བཅོས་སྡེ་བདུན་རྒྱན་གྱི་མེ་ཏོག
  author: ''
  volumes:
    a0bcea6ec18342a7a0e2e38fdaac0f2d:
      image_group_id: I1PD36355
      title: ''
      volume_number: 1
      total_pages: 532
ebook_metadata:
  title: ཚད་མའི་བསྟན་བཅོས་སྡེ་བདུན་རྒྱན་གྱི་མེ་ཏོག
  author: ''
  sku: P008018
  cover: cover.jpg
  layers:
  - pagination
