id: P008018
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W11847
  title: ཚད་མའི་བསྟན་བཅོས་སྡེ་བདུན་རྒྱན་གྱི་མེ་ཏོག
  author: ''
  volumes:
    c0f4fa1066464261adbdb30e346d0b17:
      image_group_id: I1PD36355
      title: Volume 1 of tshad ma'i bstan bcos sde bdun rgyan gyi me tog
      volume_number: 1
      total_pages: 532
      base_file: v001.txt
